apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: 238540685354.dkr.ecr.ap-south-1.amazonaws.com/sample-app
  newName: 238540685354.dkr.ecr.ap-south-1.amazonaws.com/sample-app
  newTag: c53ad4f
